import Head from "next/head";
import Image from "next/image";
import Main from "../components/Main/index";
import Music from "../components/MusicPlay";
import SideBar from "../components/SideBar";

export default function Home() {
  return (
    <div className="w-full h-full">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className="w-full h-main flex">
        <SideBar />
        <Main />
      </div>
      <Music />
    </div>
  );
}
